# Generated by Django 4.0.6 on 2022-07-14 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('bus_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
    ]
